# Generated by Django 5.2 on 2025-11-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0021_merge_20251029_2048"),
        ("simplims_app", "0024_ordemservico_resultados_servicos"),
    ]

    operations = []
