# Generated by Django 5.2 on 2025-11-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplims_app', '0025_merge_20251104_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(editable=False, max_length=50, verbose_name='Identificação')),
                ('data_coleta', models.DateField(verbose_name='Data da Coleta')),
                ('hora_coleta', models.TimeField(blank=True, null=True, verbose_name='Hora da Coleta')),
                ('local_coleta', models.CharField(max_length=100, verbose_name='Local da Coleta')),
                ('numero_ssl', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do SSL')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='simplims_app.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Amostra',
                'verbose_name_plural': 'Amostras',
                'ordering': ['-data_coleta', 'identificacao'],
            },
        ),
    ]
