# Generated by Django 5.2 on 2025-11-05 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplims_app', '0026_amostra'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='ordem_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='simplims_app.ordemservico'),
            preserve_default=False,
        ),
    ]
