# Generated by Django 5.2 on 2025-11-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplims_app', '0027_amostra_ordem_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_amostras', models.PositiveIntegerField(default=0)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_contratados', to='simplims_app.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_contratados', to='simplims_app.servico')),
            ],
        ),
    ]
