# Generated by Django 5.2 on 2025-11-05 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplims_app', '0028_servicocontratado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='servico',
        ),
        migrations.AddField(
            model_name='amostra',
            name='servico_contratado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amostras', to='simplims_app.servicocontratado'),
            preserve_default=False,
        ),
    ]
