# Generated by Django 5.2 on 2025-11-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplims_app', '0031_remove_amostra_numero_ssl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='servico_contratado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplims_app.servicocontratado'),
        ),
    ]
