# Generated by Django 5.2 on 2025-11-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplims_app', '0032_alter_amostra_servico_contratado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicocontratado',
            name='quantidade_amostras',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
