# Generated by Django 5.2 on 2026-01-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplims_app", "0036_rename_local_coleta_servicocontratado_local"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordemservico",
            options={
                "ordering": ["-data_emissao", "-id"],
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
            },
        ),
    ]
